version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hyperativa_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperativa_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: hyperativa_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql-data:
